services:
  payment-management:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    container_name: payment-management
    ports:
      - '8080:8080'
    depends_on:
      - mongo
      - wiremock
      - redis
    environment:
      - WIREMOCK_HOST=wiremock
      - WIREMOCK_PORT=8080
    volumes:
      - ./:/app
    env_file:
      - ./.env
    networks:
      - app-network

  mongo:
    image: mongo:latest
    container_name: fake-mongo
    ports:
      - '27017:27017'
    networks:
      - app-network
    volumes:
      - ./data/mongodb:/data/db

  mongo-seed:
    image: mongo:latest
    container_name: fake-mongo-seed
    depends_on:
      - mongo
    volumes:
      - './mocks/seeds:/seeds'
    entrypoint: ['bash', '/seeds/seedMongoDB.sh']
    networks:
      - app-network

  wiremock:
    image: wiremock/wiremock:latest
    container_name: wiremock
    volumes:
      - ./mocks/wiremock/mappings:/home/wiremock/mappings
      - ./mocks/wiremock/__files:/home/wiremock/__files
    networks:
      - app-network
    command: ['--verbose']

  redis:
    image: docker.io/redis:latest
    container_name: redis
    ports:
      - '6379:6379'
    volumes:
      - ./data/redis:/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodata:
    external: true
