sequenceDiagram
    title CreateWebPaymentSession
    
    participant Consumer
    participant CXS
    participant AWSCognito
    participant DynamoDb
    participant SSM
    participant GPAYO

    Consumer->>CXS: Invoke createPaymentWebSession
    Note over CXS: Validate API request
    CXS->>AWSCognito: Check if clientId has permission to use the API
    
    alt Insufficient Scope
        CXS->>Consumer: Return error code 403xx
    end

    CXS->>DynamoDb: Check if clientId exist in channels Table GET
    DynamoDb-->>CXS: Return response (channel_name)

    alt If clientId found
        alt If channel_name is "dno" or "superapp"
            Note over CXS: Check if UserToken is present and perform BAU validation
        end
    end

    alt Unauthorized
        CXS->>Consumer: Return error code 401xx
    else Bad request
        CXS->>Consumer: Return error code 400xx
    end
    
    alt When request-type is BBPrepaidPromo and channel is superapp
      Note over CXS: Set clientId to be used for GPayO interaction as cxs-dno-clientId
    end

    CXS->>SSM: Get accessToken (/cxs/<env>/gpayo/token/<clientId>)
    SSM-->>CXS: Return response

    alt If clientId not found
        CXS->>Consumer: Return error code 500xx
    end

    alt Access Token about to be expired within 5 minutes
        CXS->>SSM: Get Channel Authorization (/cxs/<env>/gpayo/credentials/<clientId>)
        SSM-->>CXS: Return response
        
        alt clientId not found
            CXS->>Consumer: Error code 500xx
        end
        
        CXS->>GPAYO: Invoke accessToken API (/auth/api/v1/accesstoken)
        GPAYO-->>CXS: Access token
        
        alt API success (http 200)
            CXS->>SSM: Save Access token (/cxs/<env>/gpayo/token/<clientId>)
        else API error (http not 200)
            CXS->>Consumer: Return error code 502xx
        end
    end

    CXS->>GPAYO: Invoke /payments/api/v1/webSession
    GPAYO-->>CXS: Return response

    alt API success (http 200)
        CXS->>DynamoDb: Insert record in customer-payments Table PUT
        DynamoDb-->>CXS: Return response
        
        alt If success
            CXS->>Consumer: Return 201 Success
        else If failed
            CXS->>Consumer: Return error code 500xx
        end
        
    else API error (http not 200)
        CXS->>Consumer: Return error code 502xx
    end