sequenceDiagram
    participant Consumer
    participant CXS
    participant Secret Manager
    participant PaymentService
    participant DB(Mongo)

    Consumer->>CXS: Invoke "CreateESIMPaymentSession"
    CXS->>CXS: Validate request

    alt If request is invalid
        CXS-->>Consumer: Return error response
    end

    alt If recommendation.type = ALLOW or TRUST or CHALLENGE
        alt If merchantId is not exists
            CXS->>Secret Manager: Get "merchantId"
            Secret Manager-->>CXS: Return "merchantId"
        end

        alt If paymentType = XENDIT
            CXS->>Secret Manager: Get "productName"
            Secret Manager-->>CXS: Return "productName"
        end

        alt If paymentType = GCASH
            CXS->>Secret Manager: Get "orderTitle"
            Secret Manager-->>CXS: Return "orderTitle"
        end

        CXS->>Secret Manager: Get "Payment Authorization Token"
        Secret Manager-->>CXS: Return "Payment Authorization Token"

        alt If Payment Authorization Token is expired or not exists
            CXS->>Secret Manager: Get "Payment Authorization Credentials"
            Secret Manager-->>CXS: Return "Credentials"

            CXS->>PaymentService: Invoke "Payment Authorization API"
            PaymentService-->>CXS: Return "Payment Authorization" response

            CXS->>DB: Save "Payment Authorization Token" and "Expiry Date"
        end

        CXS->>PaymentService: Invoke "Generic Globe Payment Service (XenditPaymentSession) Pay API" with "Payment Authorization Token"
        PaymentService-->>CXS: Return "paymentId"
        CXS->>DB: Save "paymentId and payment details"

        CXS-->>Consumer: Return success response
    else If recommendation.type = DENY
        CXS-->>Consumer: Return error response<br/>status: 400<br/>details: Unable to invoke request
    end
